using CarInsuranceBot.Application.Interfaces;
using Telegram.Bot;
using Telegram.Bot.Types;

namespace CarInsuranceBot.Application.Handlers;

// Base class for all handlers.
// Contains common logic — determines if the user asks a question
// and answers it instead of the main flow.
public class BaseHandler(
    ITelegramBotClient _botClient,
    IAiService _aiService)
{
    private const string BotDescription =
        "You are a friendly car insurance assistant in a Telegram bot. " +
        "The bot helps users purchase car insurance in a few simple steps: " +
        "1. User sends a photo of their passport. " +
        "2. User sends a photo of their vehicle registration document. " +
        "3. User confirms the extracted data. " +
        "4. User agrees to the price of 100 USD. " +
        "5. Bot generates and sends a PDF insurance policy. " +
        "Answer any questions the user has about this process clearly and helpfully. " +
        "After answering, always remind the user what step they are on and what to do next. " +
        "RESPOND IN ENGLISH ONLY.";

    protected async Task<bool> TryHandleQuestionAsync(
        Message message,
        string currentStepHint,
        CancellationToken ct)
    {
        var text = (message.Text ?? string.Empty).Trim();

        if (string.IsNullOrEmpty(text) || message.Photo is not null)
            return false;

        var isQuestionCheck = await _aiService.GetResponseAsync(
            systemPrompt: "You are a classifier. " +
                          "Determine if the user's message is a question or request for information " +
                          "about a car insurance bot process, or something unrelated to sending documents. " +
                          "Reply with only one word: YES or NO. " +
                          "Reply YES if the message is a question, clarification request, or expresses confusion. " +
                          "Reply NO if the message is a direct action like sending a photo, " +
                          "or a simple yes/no confirmation.",
            userMessage: text,
            ct: ct);

        if (!isQuestionCheck.Trim().ToUpper().StartsWith("YES"))
            return false;

        var response = await _aiService.GetResponseAsync(
            systemPrompt: "You are a friendly car insurance assistant in a Telegram bot. " +
                          "The bot helps users purchase car insurance in these steps: " +
                          "1. Send passport photo — to verify identity. " +
                          "2. Send vehicle registration document — to verify vehicle ownership. " +
                          "3. Confirm extracted data — to ensure accuracy. " +
                          "4. Agree to price of 100 USD — fixed price, no negotiations. " +
                          "5. Receive PDF insurance policy — generated by AI instantly. " +
                          "Answer the user's question clearly and helpfully. " +
                          "Explain WHY each step is needed if asked. " +
                         $"After answering, remind the user what to do now: {currentStepHint}. " +
                          "Be concise and friendly. RESPOND IN ENGLISH ONLY.",
            userMessage: text,
            ct: ct);

        await _botClient.SendMessage(message.Chat.Id, response, cancellationToken: ct);
        return true;
    }
}